### ISSUE TITLE
`__docgenInfo` object is undefined

### ISSUE THREAD

**Issue by ainalain** [strothj/react-docgen-typescript-loader#2]
Hi, I'm sorry for troubling you for the second time, I'm really excited with your plugin 😇

When I commented 'react-select' import [#1]('https://github.com/strothj/react-docgen-typescript-webpack-plugin/issues/1'), all my stories have been compiled and run well. But the was no propTypes table, although I left the comments for every prop, as Storybook Addon Info described.

After debugging I found the reason if this absence.

In your example of plugin usage, the `tsconfig.json` file defines the module type option as
 `"module": "commonjs"`. 

In our project, we use ES6 modules, so our `tsconfig.json` contains this line:
`"module": "esnext"`. 
As a result, the Info Addon doesn't recognize the __docgen object of the passed component function: the `isNotEmpty` method of `makeTableComponent` module returns `undefined`. This is because Webpack references all variables in our component with __WEBPACK_IMPORTED_MODULE\_{number}_{variableName} thing.
<img width="1076" alt="screen shot 2018-02-10 at 22 25 39" src="https://user-images.githubusercontent.com/16562120/36067397-81b951a8-0ecd-11e8-936b-ddc7f266c7d4.png">

In comparison, the check for __docgenInfo in your example works as expected:
<img width="1001" alt="screen shot 2018-02-11 at 01 21 40" src="https://user-images.githubusercontent.com/16562120/36067403-a165093e-0ecd-11e8-9269-82716924e241.png">
 
I see that the [react-docgen-typescript](https://github.com/styleguidist/react-docgen-typescript) also uses `commonjs` modules in its `tsconfig.json`. Maybe this is **react-docgen-typescript** issue, not your. Or maybe there is a known solution for my case and I didn't found it.
I'm not familiar with Webpack internal process, so for the moment, I don't know how to solve this issue.

**Comment by strothj** [comment]
Thanks for the report. I’ll take a look sometime this week.

**Comment by strothj** [comment]
Hello, I'm tracking this issue on #3. Should have a solution in not to long.

**Comment by strothj** [comment]
Closing as it is addressed by plugin.
