### ISSUE TITLE
Allow loading options from query string

### ISSUE THREAD

**Issue by tadeuszwojcik** [strothj/react-docgen-typescript-loader#22]
Hi,
Could this plugin use https://github.com/webpack/loader-utils  for loading options and not assume that passed options are always an object? It's used by docz https://github.com/pedronauck/docz/blob/master/packages/docz-core/src/bundlers/webpack/loaders.ts#L29 but passing options there as an object, makes them available to `react-docgen-typescript-loader` as a query string, not sure how to overcome that without actually changing `react-docgen-typescript-loader` to read options even if passed as query string.
Thanks!

**Comment by strothj** [comment]
@tadeuszwojcik 

Hello,

I've released a release candidate with this change.

You can review the change log here:
https://github.com/strothj/react-docgen-typescript-loader/blob/v3/README.md

The package is available as `react-docgen-typescript-loader@next`.

You might need to make use of your package manager's version override feature depending on your setup.

**Comment by tadeuszwojcik** [comment]
Thanks! I can confirm it's working fine now.

**Comment by nickmccurdy** [comment]
This should be closed by 3.0.0, right?

**Comment by strothj** [comment]
> This should be closed by 3.0.0, right?

Yes, thank you.
