### ISSUE TITLE
How to choose just specific props to be generated?

### ISSUE THREAD

**Issue by samuelcastro** [strothj/react-docgen-typescript-loader#28]
I have an ui-elements repo that extends ant-design, some components like `Button`, `Input`, etc have many native default props but I just want to document a few of them, is there a way to do that?

This is what it's generate by default:

<img width="1368" alt="screen shot 2018-10-15 at 12 36 35 pm" src="https://user-images.githubusercontent.com/5281701/46974116-f7b01d80-d077-11e8-9900-58e7244f05aa.png">

But what I really want is just a few of them.

**Comment by strothj** [comment]
You can use the PropFilter:
https://github.com/strothj/react-docgen-typescript-loader/pull/21
https://github.com/styleguidist/react-docgen-typescript/pull/111

**Comment by samuelcastro** [comment]
Awesome, thanks @strothj this fixed the problem:
```
propFilter: (prop) => {
      if (prop.parent == null) {
        return true;
      }

      return prop.parent.fileName.indexOf('node_modules/@types/react') < 0;
    }
```
