### ISSUE TITLE
Support for defaultProps declaration

### ISSUE THREAD

**Issue by caspg** [strothj/react-docgen-typescript-loader#36]
Typescript 3.0 added support for react's defaultProps declaration [click](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#support-for-defaultprops-in-jsx). 

Is there any plan to support it in this loader?

```jsx
interface ButtonProps {
  children: string
  disabled: boolean
}

Button.defaultProps = {
  disabled: false,
}

export function Button(props: ButtonProps) {
  return (
    <button className={styles.button}>
      {props.children}
    </button>
  )
}
```

Would be cool if `disabled` props would be marked as optional.

**Comment by fmal** [comment]
Would love to see this supported too, @strothj i guess this would have to be handled by https://github.com/styleguidist/react-docgen-typescript author?

**Comment by strothj** [comment]
Yes, I believe this will need to be handled by that parser package.

There’s an existing issue for it here:
https://github.com/styleguidist/react-docgen-typescript/issues/129
