### ISSUE TITLE
Type defined in another file

### ISSUE THREAD

**Issue by affanshahid** [strothj/react-docgen-typescript-loader#52]
So I am importing a type from another file and using that as a type in one of my prop declarations:

```ts
import Task, { TaskInfo } from './Task';

export interface TaskListProps {
  loading?: boolean;
  tasks?: TaskInfo[]
};
```

I get the following:
![image](https://user-images.githubusercontent.com/17955210/62389145-711deb80-b578-11e9-93d9-beeca3671ce1.png)

Notice the `any[]`. Am I doing something wrong?

**Comment by henck** [comment]
I can verify that any type declared in a different file shows up as `any`.

**Comment by sami616** [comment]
I can verify this is also happening to me

**Comment by sergiop** [comment]
@affanshahid I don't know if it's related, but with this:
```javascript

type Type = 'default' | 'action' | 'destroy'

export interface ButtonProps {
  label?: string
  type?: Type
}
```

I get the following:
<img width="820" alt="Schermata 2019-10-03 alle 23 32 06" src="https://user-images.githubusercontent.com/2235134/66165978-457db700-e636-11e9-96ff-be54ba6eb878.png">

Instead of this:
<img width="825" alt="Schermata 2019-10-03 alle 23 32 41" src="https://user-images.githubusercontent.com/2235134/66165964-3a2a8b80-e636-11e9-8925-20720703889f.png">

**Comment by kelly-tock** [comment]
this is different @affanshahid I think but I would like this as well! I have union types defined that I use in multiple places, 

```
export type TextColors = 'DEFAULT' | 'DISABLED';
```

and I just see `TextColors` as the description.

**Comment by gilbarbara** [comment]
I'm having a similar problem with union types but if I set the property as optional it expands the type...

<img width="808" alt="Screen Shot 2019-11-05 at 21 32 24" src="https://user-images.githubusercontent.com/31954/68257958-d10ead00-0013-11ea-8264-20cd892cc95f.png">

**Comment by gilbarbara** [comment]
Setting a `shouldExtractLiteralValuesFromEnum` in the loader options fixed for me.
🎉

**Comment by strothj** [comment]
For support for enums, some info can be found here:
https://github.com/strothj/react-docgen-typescript-loader/issues/87

For loading types from external files:
https://github.com/strothj/react-docgen-typescript-loader/issues/80

The documentation was recently updated to include instructions on supporting files loaded from external files. I'm closing this issue but feel free to leave a comment if this is still a problem.
