### ISSUE TITLE
Help wanted for preset CRA

### ISSUE THREAD

**Issue by mrmckeb** [strothj/react-docgen-typescript-loader#67]
Hi there,

I was working with @shilman to get `preset-create-react-app` working with this, and we're seeing an issue a few other users have reported.

One example: https://github.com/storybookjs/storybook/issues/8114

I was hoping someone from this team could take a quick look.

If you install this locally, you can see a reproduction by running:
```yarn workspace @storybook/preset-create-react-app storybook```

https://github.com/storybookjs/presets

**Comment by strothj** [comment]
The default behavior for the `react-docgen-typescript` project appears to be that it initializes a new TypeScript config using defaults if a tsconfig is not explicitly passed.

You might want to recommend setting it in your preset options:
```js
module.exports = [
  {
    name: '@storybook/preset-create-react-app',
    options: {
      scriptsPackageName: '@my/react-scripts',
      useTsDocgenLoader: true,
      tsDocgenLoaderOptions: {
        tsconfigPath: path.resolve(__dirname, "../tsconfig.json"),
    },
  },
];
```

**Comment by mrmckeb** [comment]
Thanks, I'll try this tomorrow!

**Comment by mrmckeb** [comment]
That was it, amazing - thanks @strothj!

The Babel plugin was conflicting.
