### ISSUE TITLE
Text children of components get removed

### ISSUE THREAD

**Issue by eramdam** [strothj/react-docgen-typescript-loader#7]
If one of the components importer has text children, those get removed when imported into Storybook.

See the screenshots below

<details>
<summary>Removed children</summary>
<img src="https://user-images.githubusercontent.com/1409924/36931755-6e79482e-1e71-11e8-8036-e0a4b6f8b0b4.png" />
</details>

<details>
<summary>Children being kept</summary>
<img src="https://user-images.githubusercontent.com/1409924/36931758-90a63524-1e71-11e8-8b28-1eacb22cb979.png" />
</details>

You can see that a workaround is to put whatever text into a variable and then pass that variable as the child of the elements but that's not very ideal obviously 😅 

Interestingly, I managed to reproduce the same issue in the example configuration available in the repo by applying this diff
```diff
diff --git i/example/src/components/ColorButton.stories.tsx w/example/src/components/ColorButton.stories.tsx
index 46d2b05..d59c3d5 100644
--- i/example/src/components/ColorButton.stories.tsx
+++ w/example/src/components/ColorButton.stories.tsx
@@ -2,11 +2,14 @@ import * as React from "react";
 import { storiesOf } from "@storybook/react";
 import { withInfo } from "@storybook/addon-info";
 // import ColorButton from "./ColorButton";
-import { ColorButton } from "./ColorButton";
+import { ColorButton, Dummy } from "./ColorButton";
 
 storiesOf("Components", module).add(
   "ColorButton",
   withInfo({ inline: true })(() => (
-    <ColorButton color="blue">Color Button</ColorButton>
+    <div>
+      <Dummy />
+      <ColorButton color="blue">Color Button</ColorButton>
+    </div>
   )),
 );
diff --git i/example/src/components/ColorButton.tsx w/example/src/components/ColorButton.tsx
index 1b9bd95..e46bdb8 100644
--- i/example/src/components/ColorButton.tsx
+++ w/example/src/components/ColorButton.tsx
@@ -28,4 +28,8 @@ export const ColorButton: React.SFC<ColorButtonProps> = props => (
   </button>
 );
 
+export const Dummy: React.SFC = () => <div>
+  Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates, beatae? Voluptas vero, blanditiis, maiores atque provident iste eveniet corrupti officia placeat quae pariatur aspernatur dolore dolores quia! Eos, omnis aperiam.
+</div>
+
 export default ColorButton;
```

**Comment by strothj** [comment]
Thanks for the report. I'm taking a look now.

**Comment by strothj** [comment]
I managed to reproduce the issue. The issue appears to be present when this loader is disabled. 

It appears to be an issue with the Storybook addon itself. Can you confirm?

**Comment by eramdam** [comment]
I don't. I removed the `withInfo` call from the stories files entirely and I can still see my text being removed with the loader is present in the webpack config :/ 

I uploaded the example folder below in case that helps
[example.zip](https://github.com/strothj/react-docgen-typescript-loader/files/1777800/example.zip)

**Comment by strothj** [comment]
Thank you for the reproduction, I see what you mean. I'm having a look now.

**Comment by strothj** [comment]
@eramdam Can you try version 2.0.2 ? I believe this is resolved now.

**Comment by eramdam** [comment]
@strothj Seems like it! Thanks for the quick fix! :)
