### ISSUE TITLE
Support `componentNameResolver` option from react-docgen-typescript

### ISSUE THREAD

**Issue by folz** [strothj/react-docgen-typescript-loader#71]
react-docgen-typescript accepts a `componentNameResolver` property to help resolve the component's name in edge cases, but this loader doesn't recognize that property as valid.

See https://github.com/styleguidist/react-docgen-typescript and cmd+f for `componentNameResolver`.

If you'll accept a PR to add support for this property, I'm happy to create one. Thanks!

**Comment by strothj** [comment]
Yes, in general any missing functionality from the underlying library I'd like to support. I'd be happy to accept a PR for this.

**Comment by folz** [comment]
Great, I'll have that over soon.
