### ISSUE TITLE
Awesome-typescript-loader?

### ISSUE THREAD

**Issue by julianguyen** [strothj/react-docgen-typescript-loader#8]
Does this loader work with awesome-typescript-loader?

Also thank you for this loader <3

**Comment by julianguyen** [comment]
Looks like it worked but not for latest version of awesome-typescript-loader.
Worked for: `"awesome-typescript-loader": "^3.5.0"`. I think it has to do the Webpack version that comes packaged with Storybook...

**Comment by strothj** [comment]
Storybook bundles it’s own version of Webpack. I noticed that the new ts-loader also has an issue with that version of Webpack. Not much I can do until they bump up the packaged Webpack version I think.

**Comment by strothj** [comment]
Tracking this here: https://github.com/strothj/react-docgen-typescript-loader/issues/9
