### ISSUE TITLE
Output more information on union types in prop values

### ISSUE THREAD

**Issue by dantman** [strothj/react-docgen-typescript-loader#87]
I am using [`react-docgen-typescript-loader`](https://github.com/strothj/react-docgen-typescript-loader) (docgen) with [`@storybookjs/addon-smart-knobs`](https://github.com/storybookjs/addon-smart-knobs) (smart-knobs).

If I have a component like this that uses a union of strings like an enum, then docgen does not output enough type information for smart-knobs to output a `select` knob for the prop.
```tsx
export interface StatusIndicatorProps {
  status: 'completed' | 'incomplete' | 'overdue';
}

const StatusIndicator: FC<StatusIndicatorProps> = props => {
  // ...
}
```

The resulting __docgenInfo contains the following props:

```
props: {
  status: {
    defaultValue: null,
    description: "",
    name: "status",
    required: true,
    type: {name: '"completed" | "incomplete" | "overdue"'}
  }
}
```

`smart-knobs` already has support for selects based on `PropTypes.oneOf` types. But naturally does not have support for `"completed" | "incomplete" | "overdue"` which is raw TypeScript syntax.

**Comment by dantman** [comment]
It appears that smart-knobs already has Flow support:
```js
// for flow support
if (propType.type.name === 'union' && propType.type.elements) {
  return createSelect(propName, propType.type.elements, defaultValue, propType.required)
}
```

So it may be worth considering outputting something similar. I can understand if you don't want to change `name` from the raw TypeScript union to `"union"`, but adding an alternative prop that indicates that the type is a union and including the element list would be greatly appreciated.

**Comment by strothj** [comment]
This feature can be enabled by using the option `https://github.com/styleguidist/react-docgen-typescript#parseroptions`.

```js
      {
        loader: require.resolve("react-docgen-typescript-loader"),
        options: {
          tsconfigPath: path.resolve(__dirname, "../tsconfig.json),
          shouldExtractLiteralValuesFromEnum: true,
        },
      },
```

This is documented upstream here: https://github.com/styleguidist/react-docgen-typescript#parseroptions
The relevant pull request for this package is here: https://github.com/strothj/react-docgen-typescript-loader/pull/59

This option was added specifically for enum support in addon-smart-knobs.

Let me know if you have an issue with this. Regards.
