### ISSUE TITLE
Reversal of 3.7.0

### ISSUE THREAD

**Issue by sbusch** [strothj/react-docgen-typescript-loader#89]
I just saw that [3.7.0 had been published on npm](https://www.npmjs.com/package/react-docgen-typescript-loader/v/3.7.0), but that version 3.7.0 had been "reverted", in `package.json` by commit 6f7317b1c527f9b300bb4252bef9720ae9f85aa0

You need to publish a new version since 3.7.0 is already out there in the wild and every `npm outdated` lists it as a valid upgrade (depending on semver range, for sure).

**Comment by strothj** [comment]
Hey, I actually pushed a README update for the sister project to the wrong repo. The published library itself has no changes.

**Comment by strothj** [comment]
For clarity, I've published `3.7.1` with an updated change log detailing the reversion.

**Comment by sbusch** [comment]
Thank you @strothj !
